# Generated by Django 3.0 on 2021-09-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_image_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
    ]
