# Generated by Django 3.0 on 2021-09-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20210924_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_upload',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
